[build]
  command = "cd frontend && npm install && node node_modules/react-scripts/bin/react-scripts.js build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
